services:
    karma.type_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: karma.type }

    karma.type.post:
        class: phpbb_ext_phpbb_karma_includes_type_post
        arguments:
            - @auth
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%karma # TODO put in separate file for easy configuration?
        tags:
            - { name: karma.type }

    karma.includes.karma_manager:
        class: phpbb_ext_phpbb_karma_includes_karma_manager
        arguments:
            - @karma.type_collection
            - @cache
            - @service_container
            - @dbal.conn
            - @user
            - %core.table_prefix%karma
            - %core.table_prefix%karma_types

    karma.controller.givekarma:
        class: phpbb_ext_phpbb_karma_controller_givekarma
        arguments:
            - @auth
            - @service_container
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
