services:
    karma.includes.karma_model:
        class: phpbb_ext_phpbb_karma_includes_karma_manager
        arguments:
            - @service_container
            - @dbal.conn
            - %core.table_prefix%karma

    karma.controller.givekarma:
        class: phpbb_ext_phpbb_karma_controller_givekarma
        arguments:
            - @auth
            - @service_container
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    karma.type.post:
        class: phpbb_ext_phpbb_karma_includes_type_post
        arguments:
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%karma
