services:
    karma.includes.karma_model:
        class: phpbb_ext_phpbb_includes_karma_model
        arguments:
            - @dbal.conn
            - %core.table_prefix%karma

    karma.controller.givekarma:
        class: phpbb_ext_phpbb_karma_controller_givekarma
        arguments:
            - @auth
            - @service_container
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.php_ext%
